# Generated by Django 4.1.3 on 2024-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.TextField(verbose_name='Primer texto')),
                ('second_text', models.TextField(verbose_name='Segundo texto')),
                ('about_me', models.TextField(verbose_name='Sobre mi')),
                ('project_number', models.IntegerField(verbose_name='Cantidad de proyectos')),
                ('experience_number', models.IntegerField(verbose_name='Cantidad de Experience')),
            ],
            options={
                'verbose_name': 'Pagina principal',
                'verbose_name_plural': 'Paginas principales',
            },
        ),
    ]
