# Generated by Django 4.1.3 on 2024-11-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_infohome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Razon')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('img', models.ImageField(upload_to='razones/', verbose_name='Imagen')),
            ],
        ),
    ]
