# Generated by Django 4.1.3 on 2024-11-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='reason',
            field=models.CharField(max_length=120, verbose_name='Razon'),
        ),
    ]
