# Generated by Django 4.1.3 on 2024-11-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_reasons_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Posision'),
        ),
    ]
