# Generated by Django 5.0.1 on 2024-01-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project',
            new_name='project',
        ),
    ]
