# Generated by Django 5.0.1 on 2024-01-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_project_project_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
