# Generated by Django 5.0.1 on 2024-01-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='linkendin',
            new_name='linkedin',
        ),
    ]
