# Generated by Django 5.0.1 on 2024-01-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_linkendin_socialmedia_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='socialmedia',
        ),
    ]
