# Generated by Django 5.0.1 on 2024-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.CharField(default='manual', max_length=200, verbose_name='Certificado'),
            preserve_default=False,
        ),
    ]
