# Generated by Django 5.0.1 on 2024-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=models.URLField(blank=True, verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, upload_to='experiencia/', verbose_name='Imagen'),
        ),
    ]
