# Generated by Django 4.1.3 on 2024-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='certificate',
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, upload_to='project/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='education',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL Certificado'),
        ),
    ]
