# Generated by Django 5.0.1 on 2024-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_education_certificate_alter_experience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
