# Generated by Django 5.0.1 on 2024-01-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skill_0',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='technology',
            new_name='technology_0',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Habilidad'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Habilidad'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tecnologia'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tecnologia'),
        ),
    ]
